import React from "react";
import { Authform } from "./authform";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};
const Account = () => {
  return (
    <div className="flex justify-center items-center h-screen w-full bg-gray-900">
      <Authform />
    </div>
  );
};

export default Account;
