import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import { MainNav } from "@/components/application/main-nav";
import { UserNav } from "@/components/application/user-nav";
import { cn } from "@/lib/utils";
import { Search } from "lucide-react";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import Navbar from "@/components/layouts/nav-bar/navbar";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient();
  const { data, error } = await supabase.auth.getUser();
  if (error || !data?.user) {
    redirect("/auth/login");
  }

  return (
    <html lang="en">
      <body className={cn("font-sora", sora.variable)}>
        <div className="flex flex-col place-items-center justify-start w-full min-h-screen bg-slate-200 relative">
          <Navbar />
          <div className="w-full flex justify-center py-4">{children}</div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
