import type { Metadata } from "next";
import { Sora } from "next/font/google";
import Navbar from './components/Navbar';
import "./globals.css";

const inter = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
       
      </head>
      <body className={inter.className}>
     
        <Navbar />

      
        <div id="main-container " className="flex w-full h-screen bg-gray-900 ">
          
          {children}
        </div>
      </body>
    </html>
  );
}
